// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4SMSWNhx1tI9WQeRB7R0yhruMZ15mXZA',
    appId: '1:988800405363:android:30012b10e4b9036be93f06',
    messagingSenderId: '988800405363',
    projectId: 'canteenapp-ecc48',
    storageBucket: 'canteenapp-ecc48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw42QPDVyf5TQzkQzSyjC_c1moxWigFpM',
    appId: '1:988800405363:ios:8b9767ccd8639d2ee93f06',
    messagingSenderId: '988800405363',
    projectId: 'canteenapp-ecc48',
    storageBucket: 'canteenapp-ecc48.appspot.com',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSiAj3HISafPfzXbVAsxJ0W4TLZLnW2DM',
    appId: '1:988800405363:web:a5d60e431ea3fda2e93f06',
    messagingSenderId: '988800405363',
    projectId: 'canteenapp-ecc48',
    authDomain: 'canteenapp-ecc48.firebaseapp.com',
    storageBucket: 'canteenapp-ecc48.appspot.com',
    measurementId: 'G-XMVCJSDSHP',
  );
}
